### ISSUE TITLE
Cannot deploy with Webpack - Unexpected token in 

### ISSUE THREAD

**Issue by GitHubGreg** [jcoreio/redux-form-normalize-on-blur#5]
After installing this package and trying to deploy my project, I now get this error:

```
ERROR in assets/js/index.e28b.js from UglifyJs
Unexpected token: keyword (const) [./node_modules/redux-form-normalize-on-blur/es/index.js:20,0][assets/js/index.e28b.js:5843,0]
```

Thanks in advance for any help.

**Comment by jedwards1211** [comment]
Ah use a webpack rule to transpile this package

**Comment by GitHubGreg** [comment]
Could you elaborate on that please?

**Comment by GitHubGreg** [comment]
Have been trying to resolve this for about an hour with no luck. Babel 7+ excludes node_modules by default, and including a single package throws errors (lots of forum posts about similar issues but no solution that has worked so far). Any chance you'd consider updating this package to be already transpiled?

**Comment by GitHubGreg** [comment]
For anyone else having this issue, I resolved it by switching from uglify to terser, as per [this suggestion](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/362#issuecomment-425849160). 

Since this is for redux-form, perhaps consider writing this package with the same ecma standards as the redux-form package.

**Comment by jedwards1211** [comment]
Yeah i think I will get rid of the half-transpiled code when I get a chance.  I had added that to a bunch of my packages for the sake of making builds for modern browsers smaller, but I think it's just too much trouble for people.  Terser probably works because it understands ES6.  But the output code would probably still not work in old browsers.  Sorry this has caused you grief, when I get back to my computer I'll switch it to full transpiling.

**Comment by GitHubGreg** [comment]
Great thanks, I appreciate this helpful package.
